DEFINE	C:	LIB02:<COS.LEPREAU>
DEFINE	C3:	LIB02:<COS.LEPREAU.3>
DEFINE	C3L:	LIB02:<COS.LEPREAU.3.LOCAL>
DEFINE	C3M:	LIB02:<COS.LEPREAU.3.MOD>
DEFINE	CP:	LIB02:<COS.LEPREAU.CPP>
DEFINE	CPD:	LIB02:<COS.LEPREAU.CPP.DIST>
DEFINE	CS:	LIB02:<COS.LEPREAU.SUPPORT>
