An interim version (NOT a "release") of the University of Utah's Unix
Portable C Compiler, pcc, is now available on the Dec-20, generating 20 code.
At the moment, its primary virtues are that it accepts full v7 Unix C, and
has a run-time system which includes many of the standard Unix library
routines and system calls.  Over 125 Unix library routines are now available;
see <PCC.DOC>STATUS.SUMMARY for some details.  The run-time library supports
command line file re-direction and filename expansion a la Unix.  A PCL
driver procedure is provided; do HELP PCC and see the the other files on
<PCC.DOC> for more information.
